[package]
name = "sshmount"
version = "0.1.0"
edition = "2021"
authors = ["mito"]
description = "ssh接続先のディレクトリをマウントする"
license = "GPLv3"
keywords = ["utility", "filesystem", "linux", "ssh", "sftp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.30", features = ["derive"] }
