name: Rust CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install fuse3
        run: sudo apt-get install -y libfuse3-dev

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --all-features

      - name: Check formatting
        run: cargo fmt --all --check
